name: rouxinol
channels:
  - pytorch
  - defaults
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - gawk
  - libstdcxx-ng
  - graphviz
  - capstone
  - automake
  - cmake
  - pytorch-cpu
  - tensorflow
  - dgl=2.3.0=py310h039f8d5_0
  - pip
  - pip:
    - absl-py
    - appdirs
    - gitpython
    - networkx
    - pandas
    - pytest
    - pygraphviz
    - ir2vec==2.1.0
    - lief=0.13.2
    - pyaml
    - typing-extensions
    - scikit-learn
    - sympy
    - xgboost-cpu
    - wget
    - seaborn
    - shap
    - optuna

