name: rouxinol
channels:
  - pytorch
  - defaults
  - anaconda
  - conda-forge
  - bioconda
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - cuda=12.2.2
  - cuda-tools=12.2.2
  - cuda-toolkit=12.2.2
  - cuda-version=12.2
  - cuda-command-line-tools=12.2.2 
  - cuda-compiler=12.2.2 
  - cuda-runtime=12.2.2
  - gawk
  - libstdcxx-ng
  - graphviz
  - capstone
  - automake
  - cmake
  - pytorch-gpu
  - tensorflow-gpu
  - dgl
  - clang=12.0.0
  - clang-tools=12.0.0
  - clangdev=12.0.0
  - clangxx=12.0.0
  - libclang=12.0.0
  - libclang-cpp=12.0.0
  - libllvm12=12.0.0
  - llvm=12.0.0
  - llvm-tools=12.0.0
  - llvmdev=12.0.0
  - pip
  - pip:
    - absl-py
    - appdirs
    - gitpython
    - networkx
    - pandas
    - pytest
    - pygraphviz
    - ir2vec==2.1.0
    - lief=0.13.2
    - pyaml
    - typing-extensions
    - scikit-learn
    - sympy
    - xgboost
    - wget
    - seaborn
    - shap
    - optuna
